### ISSUE TITLE
Create a tool for automatic update versions

### ISSUE THREAD

**Issue by phracek** [sclorg/container-common-scripts#135]
The aim of the tool, in Python, would be to do the following things.

- [ ] Automatically update upstream SCL GitHub repository to the new
- [ ] Copy / create a directory structure like is mentioned here https://github.com/sclorg/welcome/blob/master/contribution.md#adding-a-new-version
- [ ] It would be nice to run also tests on all architectures, like Fedora, CentOS, RHEL
- [ ] Store output into the JSON file. What failed, what was successful
- [ ] TBD

**Comment by pkubatrh** [comment]
example PR: https://github.com/sclorg/s2i-php-container/pull/261/commits

**Comment by phracek** [comment]
This will be solved by this issue https://github.com/sclorg/container-workflow-tool/issues/10
