### ISSUE TITLE
It looks like command not found

### ISSUE THREAD

**Issue by phracek** [sclorg/container-common-scripts#180]
It looks like `command` not found in the test suite.

https://gist.github.com/rhscl-automation/a424c41937ec2b077b74bbab1c7b56e3#file-s2i-ruby-container-231-sh-L12574

**Comment by pkubatrh** [comment]
Unlikely `command` is missing, considering there is no call to `command` anywhere I can see. From the line numbers my guess would be that the definitions of `ct_` have not been found for some reason.

**Comment by pkubatrh** [comment]
Or, its actually ` ` which is missing (as in the "space" command)
