### ISSUE TITLE
Symlink loop

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/container-common-scripts#205]
I'm using Vagrant for testing and it rejects to sync common scripts to the virtual machine (using rsync) because there is an infinite loop of symlinks: `common/tests/failures/check` contains `common` which is a symlink back to `../../..` which causes this loop:

```
common/tests/failures/check/common/tests/failures/check/common/tests/failures/check/common/tests/failures/check/common…
```
Is this something we need to have here?

**Comment by phracek** [comment]
This was introduced by https://github.com/sclorg/container-common-scripts/pull/60.

**Comment by praiskup** [comment]
I barely remember why I did this, but it was to make the test suite work in this repo.

Why rsync complaints?  Do you really need to use rsync -L ?

**Comment by frenzymadness** [comment]
You are right, I can reconfigure Vagrant to either ignore that folder or do not use the `--copy-links` default option: https://www.vagrantup.com/docs/synced-folders/rsync#options

But, and it might be just my feeling, symlink loops are weird and I'd rather avoid them, if possible. And according to the proposed change, it should be possible and it also tests a way of use that has not been tested before.
