### ISSUE TITLE
RHEL7 build issue: installing docker_py=1.10.6 fails

### ISSUE THREAD

**Issue by praiskup** [sclorg/container-common-scripts#22]
Seems like this is result of some work-around from 5fe4cbbea27b2299e61e889f78414a9ec65ee70a commit.   But explicitly installing v1.10.6 fails for me with:

```
$ easy_install -q --user docker_py==1.10.6 docker-squash==1.0.5
error: Setup script exited with error in docker-py setup command: Invalid environment marker: python_version < "3.5"
```

OTOH, `easy_install -q --user docker-squash==1.0.5` works just fine. Do we still need explicit version of docker_py?

**Comment by omron93** [comment]
I don't see reason for this workaround - it is quite old so I guess a problem could be fixed now.
