### ISSUE TITLE
Print info about container image tested in test.sh

### ISSUE THREAD

**Issue by zmiklank** [sclorg/container-common-scripts#300]
So that from the logs could be clearly seen, which OS is tested, which VERSION and which container image.

**Comment by frenzymadness** [comment]
The reason for this is that the first page you see when you open a test result does not contain any info about container image name or version. Only OS is there in the red header.
![image](https://user-images.githubusercontent.com/5688939/193522648-bcf9b496-d323-4eaf-92dd-357765b17a4b.png)

**Comment by zmiklank** [comment]
Related issue: https://github.com/teemtee/tmt/issues/1583

**Comment by zmiklank** [comment]
Current state:
![image](https://user-images.githubusercontent.com/90186537/226836196-14e5ba85-3619-4d23-b4b9-f85a13784753.png)

Is this sufficient?
