### ISSUE TITLE
generator.py fails the sanity check

### ISSUE THREAD

**Issue by zmiklank** [sclorg/container-common-scripts#311]
I just now noticed, that the newly added `generator.py` introduced a few errors in the sanity check[1].

@frenzymadness would you please find a time to look into it, or should I do it?

[1] https://github.com/sclorg/container-common-scripts/actions/runs/3471587751/jobs/5801281024

**Comment by frenzymadness** [comment]
I see, so the problem is that the generator does not have type annotations. I can add them next week. The question is why the failed check didn't make the linked task fail?

**Comment by zmiklank** [comment]
Because it only sets the status as failed in the PR, but the action itself does not fail.
But here is a PR for fixing that: https://github.com/sclorg/container-common-scripts/pull/310

> I see, so the problem is that the generator does not have type annotations. I can add them next week. 

Great, thank you.
