### ISSUE TITLE
avoid testing everything for each PR

### ISSUE THREAD

**Issue by praiskup** [sclorg/container-common-scripts#32]
It would be nice to be able to selectively pick particular VERSIONs for remote images, e.g.  And later even the test-cases.

**Comment by phracek** [comment]
For testing the latest image streams we have similar functionality here: https://github.com/sclorg/container-common-scripts/blob/master/test-lib.sh#L796

I guess we can test the latest version and if it is excluded the version which is not the latest.

**Comment by phracek** [comment]
Closing. This issue was discussed and we would like to have tested all VERSIONS.
