### ISSUE TITLE
Do not try to get compressed image size when tests are interrupted

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/container-common-scripts#337]
When I run tests locally and I want to kill them early (through SIGINT) the cleanup phase starts, including compressing the image to check its size. This can take a while to complete when the image is larger, so it would make sense to skip this part when the tests are interrupted early.

**Comment by zmiklank** [comment]
Probably connected to: https://github.com/sclorg/container-common-scripts/issues/327.

We can set different traps on SIGINT and EXIT and that would solve the issue.

**Comment by zmiklank** [comment]
I think this is good first issue.

**Comment by zmiklank** [comment]
I've proposed PR, which at least adds a log entry, that the cleanup takes some time, so the user know.
I know it is not a fix, but I was doing something else in `test-lib.sh` and thus had a good opportunity to add such a commit there.

**Comment by zmiklank** [comment]
Proper fix should be here: https://github.com/sclorg/container-common-scripts/pull/338
