### ISSUE TITLE
Migrate fedora images to f38 where possible

### ISSUE THREAD

**Issue by zmiklank** [sclorg/container-common-scripts#347]
- httpd-container https://github.com/sclorg/httpd-container/pull/188
- nginx-container https://github.com/sclorg/nginx-container/pull/261
- s2i-php-container - not possible here
- varnish-container https://github.com/sclorg/varnish-container/pull/126
- mariadb-container https://github.com/sclorg/mariadb-container/pull/209
- postgresql-container - done in PR together with centos7 changes
- s2i-nodejs-container https://github.com/sclorg/s2i-nodejs-container/pull/399
- s2i-python-container - already done
- mysql-container https://github.com/sclorg/mysql-container/pull/346
- redis-container https://github.com/sclorg/redis-container/pull/150
- s2i-perl-container https://github.com/sclorg/s2i-perl-container/pull/276
- s2i-ruby-container https://github.com/sclorg/s2i-ruby-container/pull/493 
- s2i-base-container  - already done

**Comment by phracek** [comment]
@zmiklank Why s2i-php-container is not possible? Because PHP-8.2 does not exist in s2i-php-container?

**Comment by zmiklank** [comment]
php 8.1 seem to be available in f37 at latest - f37 is also still supported. The version of php in f38 is 8.2 and we do not have php 8.2 Fedora image yet. There is currently no plan to proactively adding it. 
Do you think it should be added?

**Comment by phracek** [comment]
Everything was done. CLosing.

**Comment by zmiklank** [comment]
I am sorry, I did not remove nodejs Centos7 deprecation PR from the list when I removed Fedora changes from it.
I need to reopen this issue, as nodejs container needs to be additionally addressed.
