### ISSUE TITLE
common/build.sh: line 34: syntax error near unexpected token `;;'

### ISSUE THREAD

**Issue by omron93** [sclorg/container-common-scripts#35]
Reported in https://github.com/sclorg/s2i-python-container/issues/220. So moving there.

> on mac osx 10.12.6
$make build TARGET=centos7 VERSIONS=2.7
> VERSION="2.7" SKIP_SQUASH=1 UPDATE_BASE= OS=centos7 CLEAN_AFTER= DOCKER_BUILD_CONTEXT=. OPENSHIFT_NAMESPACES="3.3" common/build.sh
common/build.sh: line 34: syntax error near unexpected token `;;'
make[1]: *** [2.7] Error 2

**Comment by praiskup** [comment]
Resp. it looks like the `>( )` construct isn't recognized by your bash; can you post the output from `echo >(:)` so we can see that shell-managed fifo is created?

**Comment by evilbinary** [comment]
[evil]$echo >(:)
/dev/fd/63
[evil]$bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

I found that   $( case statment )  not support.

**Comment by praiskup** [comment]
Ah, OK -> seems like older bashes had problems with `echo $(case x in x) echo x ;; esac)`, parser probably takes the first closing `)` bracket as end of '$()'.

How difficult is to install up2date bash (version 4+) on your box?

**Comment by afnan9632** [comment]
Hey please help ne solve this error
./phish.sh: line 430: syntax error near unexpected token `;;'
./phish.sh: line 430: `                ;;'

**Comment by snowtta** [comment]
./phish sh: line 430:,...,
