### ISSUE TITLE
grep: warning: stray \ before -

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/container-common-scripts#353]
It seems to me that the warning (grep: warning: stray \ before -) we are getting in the CI of Python container comes from this line:

https://github.com/sclorg/container-common-scripts/blob/250ae7c6b9312e2389b08d349a1a95c59ed1dde9/test-lib.sh#L928

It seems to be a new feature of grep 3.8. I'm not an expert here but it seems that a single slash at the beginning of the string is enough

**Comment by zmiklank** [comment]
++ I came to this warning too, came to conclusion that it makes no harm and decided to let it be as it is.
However...now it seems that I am not the only person who spent a time on this which means it would be benefitial to either fix the warning or silence it.

Your suggestion seems correct, however we should probably check how this behave in older bashes too. Do you want to create PR for this or shall I?

**Comment by frenzymadness** [comment]
I'm on PTO now so feel free to take it over.

**Comment by zmiklank** [comment]
tested ` echo "$s2i_args" | grep -q "\--incremental" && incremental=true ` on CentOS7, and it works. PR will follow shortly.
