### ISSUE TITLE
Use imagestream generator for editing imagestream json files

### ISSUE THREAD

**Issue by zmiklank** [sclorg/container-common-scripts#364]
- [x] httpd-container https://github.com/sclorg/httpd-container/pull/205
- [x] nginx-container
- [x] s2i-php-container https://github.com/sclorg/s2i-php-container/pull/441
- [x] varnish-container https://github.com/sclorg/varnish-container/pull/140
- [x] mariadb-container https://github.com/sclorg/mariadb-container/pull/232
- [x] postgresql-container https://github.com/sclorg/postgresql-container/pull/549
- [x] s2i-nodejs-container https://github.com/sclorg/s2i-nodejs-container/pull/427
- [x] s2i-python-container https://github.com/sclorg/s2i-python-container/pull/678
- [x] mysql-container https://github.com/sclorg/mysql-container/pull/371
- [x] redis-container https://github.com/sclorg/redis-container/pull/173
- [x] s2i-perl-container https://github.com/sclorg/s2i-perl-container/pull/305
- [x] s2i-ruby-container https://github.com/sclorg/s2i-ruby-container/pull/547
- [x] s2i-base-container - N/A. Neither s2i-base nor s2i-core containers have imagestreams.
- [x] create github action to check, if streams are up to date

**Comment by phracek** [comment]
Closing all issues were covered.
