### ISSUE TITLE
`ct_os_install_in_centos` function is not used

### ISSUE THREAD

**Issue by hhorak** [sclorg/container-common-scripts#53]
`ct_os_install_in_centos` function is not used in:
https://github.com/sclorg/container-common-scripts/blob/6fb3efbb25c731a92c440763d239eab4d5733c26/test-lib-openshift.sh#L284

However, instead of removing it, it might be good to have a binary (e.g. `ct-centos-prepare-machine`, similarly can be then `ct-fedora-prepare-machine`) in common scripts that would call this function. But this must be consulted before, since I'm personally not sure whether this will be useful.

**Comment by phracek** [comment]
This function does no exists:

```
$ grep -rn 'install_in_centos' *
$

Closing.
