### ISSUE TITLE
Remove temporary hidden files before build

### ISSUE THREAD

**Issue by omron93** [sclorg/container-common-scripts#79]
Hidden files `.image-id` and `.image-id.raw` are not removed after build.

So in scenario:
1. `make test TARGET=centos7`
2. `make test TARgET=fedora`

Fedora is not supported for all versions. But the second point uses the hidden files from previous build and for some versions it tests centos based images.

Also for some images these hidden files are in .gitignore, so user can't be even aware that some old files needs to be cleaned.

**Comment by pkubatrh** [comment]
I do not think it would be a good idea to remove these files before running the build - we are doing some best-effort clean up actions using the hidden image-id files...
However, it would make sense to me to try and run the clean up action in case the build script runs into a configuration that could not be built but there is an image-id file already present. Will prepare a PR for discussion.
