### ISSUE TITLE
Use :: for library separation

### ISSUE THREAD

**Issue by hhorak** [sclorg/container-common-scripts#80]
https://google.github.io/styleguide/shell.xml#Function_Names suggests to use `::` separator for libraries separation, so we can end up with something like:

```
ct::os::print_logs "some"
```
instead of
```
ct_os_print_logs "some"
```

**Comment by hhorak** [comment]
I wanted just to hear more opinions, not that I'd push on that either. Thanks for the feedback so far, I'd keep this open to see more feedback, but I agree that without a good reason to change it, it's not worth it.

**Comment by omron93** [comment]
In my point of view, portability of this project isn't so important. But I'm also thinking if the readability of the new format is so better, that it makes sense to rewrite tests for several images...

**Comment by pkubatrh** [comment]
Imo the readability improves by a bit but I do not think it is worth the change, considering we would need to change all of the images to the new format (or keep both for compatibility I guess)

**Comment by hhorak** [comment]
I agree it's not worth it, closing.
