### ISSUE TITLE
make: specs/multispec.yml should be in deps for each distgen rule

### ISSUE THREAD

**Issue by praiskup** [sclorg/container-common-scripts#87]

**Comment by phracek** [comment]
I don't follow this pull request. distgen containers are checked by GitHub Action.

In case this issue is still valid feel free to re-open it.

We do not have enough resources to fixing it.

**Comment by frenzymadness** [comment]
As I understand it, Pavel wants distgen to run before every other action in make which would prevent building container images from outdated sources - that might happen if you forget to regenerate then after you change the specs and templates and before you build the image.
